/camera/c922_camera:
  ros__parameters:
    video_device: "/dev/video0"
    image_size: [640, 480]
    pixel_format: "YUYV"
    output_encoding: "yuv422_yuy2"
    framerate: 30.0

    focus_auto: false
    focus_absolute: 0

    brightness: 128
    contrast: 128
    saturation: 128
    sharpness: 128

    image_raw_topic: "image_raw"