python_snn_node:
  ros__parameters:
    # Input from encoder_node
    input_mode: "packed"
    input_topic: "/snn/input"
    pack_order: ["proximity", "keypoints_grid"] # add more channels here when they are implemented in encoder_node (proximity_stop, etc.)

    # Channel sizes, must match encoder_node's output
    proximity_size: 1
    keypoints_grid_size: 12   # <-- adjust to match encoder_node's number of cells in grid
    object_rec_size: 3

    # Output actions from SNN
    num_actions: 3   # LEFT, FORWARD, RIGHT

    # Timer and stop conditions
    timer_hz: 30.0
    idle_timeout_sec: 1.0

    # proximity stop logic
    use_proximity_for_stop: false # if true, proximity=1 means "emergency stop, too close to obstacle"
    proximity_stop_active_high: true # no effect as long as use_proximity_for_stop=false

    # Robot speed settings
    forward_speed: 0.25 # m/s
    turn_speed: 0.6 # rad/s

    ##### Neuron parameters #####
    decay: 0.75
    threshold: 4.0
    reset: 0.0

    ##### Synapse parameters #####
    training_mode: true # Remove?
    learning_rate: 0.250
    initial_weight: 0.3
    t_pre: 3
    t_post: 3
    tau_e_shift: 4
    dw_pos: 0.25
    dw_neg: 0.03125
    min_weight: 0.03125
    max_weight: 1.0
    dopamine_correct: 1.0
    dopamine_wrong: -0.5


    seed: 42 # for reproducibility, or null for random.
