python_snn_node:
  ros__parameters:
    # Input from encoder_node
    input_mode: "packed"
    input_topic: "/snn/input"
    pack_order: ["keypoints_grid", "proximity", "object_rec"] # add more channels here when they are implemented in encoder_node (proximity_stop, etc.)

    # Channel sizes, must match encoder_node's output
    keypoints_grid_size: 24   # <-- adjust to match encoder_node's number of cells in grid
    proximity_size: 4
    object_rec_size: 5

    # Output actions from SNN
    num_actions: 3   # LEFT, FORWARD, RIGHT

    # Timer and stop conditions
    timer_hz: 30.0
    idle_timeout_sec: 1.0

    # Robot speed settings
    forward_speed: 0.125 # m/s
    turn_speed: 0.3 # rad/s

    ##### Neuron parameters #####
    decay: 128
    threshold: 1024
    reset: 0

    ##### Synapse parameters #####
    lr_shift: 3 
    initial_weight: 64
    t_pre: 3
    t_post: 2
    tau_e_shift: 3
    dw_pos: 64
    dw_neg: 32
    min_weight: 8
    max_weight: 255
    feedback: True
    learning_mode: 'rstdp' # 'None', 'stdp', 'rstdp'


    seed: 42 # for reproducibility, or null for random.
